@echo off
echo Restarting all development servers...

echo Stopping Node.js servers (backend, dashboard, frontend)...
taskkill /F /IM node.exe

echo Waiting for processes to terminate...
timeout /t 3 /nobreak > nul

echo Starting all servers again...
call start-all-servers.bat

echo All servers have been restarted.